# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24a38b48ce6921555e23e5f28da60d8a92e1e741bffb9cea242978205a7ff18ec5fe54abf13738cc41e757b0cd1d680d6f3ac8185485c4362e7b3b2a5662a045

test:
  secret_key_base: 46bde72786f95a311a96b9fadfd923ebc6793fbab2b544ee1142492e0c1c0d2f95d52f47a8bcc37e982d54cb519de21eee49230eb294e9551007de049acb6530

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
